# Generated by Django 3.2.16 on 2023-02-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_alter_member_options"),
        ("byro_groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembers",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="byro_groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupmembers",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="members.member",
            ),
        ),
    ]
