# Generated by Django 3.2.16 on 2023-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byro_groups", "0002_auto_20230207_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="subgroups",
            name="groupid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="subgroups",
            name="subgroupid",
            field=models.IntegerField(null=True),
        ),
    ]
