# Generated by Django 3.2.16 on 2023-02-24 12:52

import byro.common.models.log
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_alter_member_options"),
        ("byro_groups", "0003_auto_20230208_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMemberRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            bases=(models.Model, byro.common.models.log.LogTargetMixin),
        ),
        migrations.CreateModel(
            name="SubGroupRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="groupmembers",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmembers",
            name="member",
        ),
        migrations.DeleteModel(
            name="SubGroups",
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="GroupMembers",
        ),
        migrations.AddField(
            model_name="subgrouprelation",
            name="groupid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_group",
                to="byro_groups.group",
            ),
        ),
        migrations.AddField(
            model_name="subgrouprelation",
            name="subgroupid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_group",
                to="byro_groups.group",
            ),
        ),
        migrations.AddField(
            model_name="groupmemberrelation",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="byro_groups.group",
            ),
        ),
        migrations.AddField(
            model_name="groupmemberrelation",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="members.member",
            ),
        ),
    ]
