# Generated by Django 3.2.16 on 2023-02-27 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("byro_groups", "0004_auto_20230224_1252"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subgrouprelation",
            old_name="groupid",
            new_name="main_group",
        ),
        migrations.RenameField(
            model_name="subgrouprelation",
            old_name="subgroupid",
            new_name="subgroup",
        ),
    ]
